name: Publish to GCP Artifact Registry (admi)
on:
  release:
    types: [ created ]
  workflow_dispatch:
  push:
    branches:
      - admi-main

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - id: "auth"
        uses: "google-github-actions/auth@v2"
        with:
          credentials_json: "${{ secrets.GCP_CREDENTIALS }}"

      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v2"

      - name: "Use gcloud CLI"
        run: "gcloud info"

      - uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'temurin'
          server-id: artifact-registry

      - run: mvn -B -ntp deploy -f engine/pom.xml
